version: '3'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/server.conf:/etc/nginx/server.conf:ro
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./:/var/www

